services:
  whisperx-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: whisperx-service
    container_name: whisperx-container
    env_file:
      - .env
    ports:
      - "5001:8000"
    volumes:
      - "/data/whisperx/cache:/root/.cache"
      - "/data/whisperx/tmp:/tmp"
volumes:
  whisperx-models-cache:
  whisperx-app-volume:
